### ISSUE TITLE
Code snippet below node is mostly unreadable

### ISSUE THREAD

**Issue by bkiefer** [bkiefer/GraVE#10]
Either the size should be adapted to the really needed size, or there should be a "visible part".
BK: I think i prefer the first. We can still think about something else if that turns out to be not
feasible.

**Comment by aWelker** [comment]
The size is now being adapted; however, I left the maxWidth and maxHeight variables in CmdBadge to prevent the text display from exploding all over the screen.
Should they stay or go away? Even if they stay, they should probably move to EditorConfig (or Preferences?).

**Comment by bkiefer** [comment]
They should definitely stay, and maybe move to EditorConfig.

**Comment by bkiefer** [comment]
Thinking about the possibility to use zero or -1 for "unrestricted"

**Comment by bkiefer** [comment]
Fixed
