### ISSUE TITLE
Undo/Redo fails if switching to different SuperNode

### ISSUE THREAD

**Issue by bkiefer** [bkiefer/GraVE#28]
This could be fixed by clearing the UndoManager, but maybe that's not what's desired.

**Comment by aWelker** [comment]
Alternatively: Each SuperNode could maintain its own UndoManager. This would allow to switch between different parts of the graph and always be able to undo changes you did to the current environment

**Comment by bkiefer** [comment]
To reproduce:
 - Create supernode, change into supernode, undo: NullPointerException
 - Create supernode, change into supernode, create node, change to parent,  undo, undo --> node created in new supernode is now in parent

**Comment by bkiefer** [comment]
Possible solutions:
1. separate Undo managers for all active super nodes
    - When the supernode stack is "popped", the undo managers for the respective supernodes are dropped or not?
    - That would mean that you can only undo things in the current supernode
2. The actions get a SuperNode field and act on the right model.
     - Issue a warning if undoing/redoing things outside the current view!?
3. Changing the SuperNode clears the undo/redo manager. This might be an interim solution until there is a better one

**Comment by bkiefer** [comment]
Possible solutions:
1. separate Undo managers for all active super nodes
    - When the supernode stack is "popped", the undo managers for the respective supernodes are dropped or not?
    - That would mean that you can only undo things in the current supernode
2. The actions get a SuperNode field and act on the right model.
     - Issue a warning if undoing/redoing things outside the current view!?
3. Changing the SuperNode clears the undo/redo manager. This might be an interim solution until there is a better one

**Comment by bkiefer** [comment]
fixed by 5d979d71b6a45b6838cb00e20e8e695d61a53c8c
